import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Hero",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="h-screen">
          {children}
        </div>


        <footer className="footer footer-center bg-black text-white text-base-content p-4 text-center">
          <aside>
            <p>Copyright © {new Date().getFullYear()} - All right reserved by Next HEro</p>
          </aside>
        </footer>


      </body>
    </html>
  );
}
